# Generated by Django 4.0.1 on 2022-01-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='video/')),
                ('convert_to', models.CharField(choices=[('.mp4', 'MP4'), ('.avi', 'AVI'), ('.mov', 'MOV')], default='.mp4', max_length=6)),
            ],
        ),
    ]
