# Generated by Django 3.2.7 on 2021-12-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211224_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
