# Generated by Django 3.2.7 on 2022-01-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='convert_to',
            field=models.CharField(default='.png', max_length=6),
        ),
    ]
