# Generated by Django 3.2.7 on 2022-01-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesapp', '0002_image_convert_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='convert_to',
            field=models.CharField(choices=[('.jpg', 'JPG'), ('.png', 'PNG')], default='.png', max_length=6),
        ),
    ]
